[package]
name = "bmcd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"

log.workspace = true
simple_logger.workspace = true
