name: 'Cargo CI'
on: push

jobs:
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update &&\
          sudo apt-get install libusb-1.0-0-dev -y
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          args: '--all-features -- -D warnings'
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: test
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check bans licenses sources
